spring :
  application:
    name : api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

server :
  port : 8001
eureka :
  client :
    serviceUrl :
      defaultZone : http://localhost:8761/eureka