spring :
  data :
    mongodb :
      uri : ${DB_URI}
      database : ${DB_DATABASE}

  application:
    name: auth

server:
  port: 7070

eureka :
  client :
    serviceUrl :
      defaultZone : http://localhost:8761/eureka